AWSTemplateFormatVersion: 2010-09-09

Description: Amazon EBS volume is a durable, block-level storage device that you can attach to your instances. After you attach a volume to an instance, you can use it as you would use a physical hard drive.
Metadata:
  AWS::CloudFormation::Interface:    
    ParameterGroups:
      - Label:
          default: EBS Configuration
        Parameters:
          - VolumeType
          - VolumeSize
          - Iops
          - Throughput
          - AvailabilityZone
          - Encrypted
          - KmsKeyId
Parameters:
  VolumeType:
    Description: If the volume type is io1 or io2, you must specify the IOPS that the volume supports.
    Type: String
    AllowedValues: [gp2, gp3, io1, io2, sc1, st1, standard]
    Default: standard
  VolumeSize:
    Description: >- 
      The size of the volume, in GiBs. You must specify either a snapshot ID or a volume size. If you specify a snapshot, the default is the snapshot size. You can specify a volume size that is equal to or larger than the snapshot size.
      The following are the supported volumes sizes for each volume type:
      gp2 and gp3:1-16,384
      io1 and io2: 4-16,384
      st1 and sc1: 125-16,384
      standard: 1-1,024
    Type: Number
    Default: 100
  Iops:
    Description: >-
      The number of I/O operations per second (IOPS). For gp3, io1, and io2 volumes, this represents the number of IOPS that are provisioned for the volume.
      applicable only if VolumeType selected is gp3,io1 or io2.
      gp3: 3,000-16,000 IOPS
      io1: 100-64,000 IOPS
      io2: 100-64,000 IOPS
    Type: Number
    Default: 3000
  Throughput:
    Description: The throughput to provision for a gp3 volume, with a minimum of 125  MiB/s or a maximum of 1,000 MiB/s.
    Type: Number
    MaxValue: 1000
    MinValue: 125
    Default: 125
  AvailabilityZone:
    Description: choose the Availability Zone in which to create the volume. A volume can be attached only to  instances that is in the same Availability Zone.
    Type: AWS::EC2::AvailabilityZone::Name    
  Encrypted:
    Description: Indicates whether the volume should be encrypted.
    Type: String
    AllowedValues: [true, false]
    Default: false
  KmsKeyId:
    Description: >-
      The ID of the AWS Key Management Service (AWS KMS) key used to encrypt Amazon Elastic Block Store (Amazon EBS) volume.
      applicable only when AWS KMS key is available and Encryption is set to true.
    Type: String
    Default: NONE
     
  ResearcherName:
    Description: Researcher name that will be added as tag to the resources.
    Type: String
  ProjectId:
    Description: Project Id that will be added as tag to the resources.
    Type: String
  Namespace:
    Description: An environment name that will be prefixed to resource names.
    Type: String
    

Conditions:
  KMSKeyNotProvided: !Equals [!Ref KmsKeyId, 'NONE']
  IopsVolumeType: !Or [!Equals [!Ref VolumeType, gp3],!Equals [!Ref VolumeType, io1],!Equals [!Ref VolumeType, io2]]
  ThroughputApplicable: !Equals [!Ref VolumeType, gp3]

Resources:
  VolumeId:
    Type: AWS::EC2::Volume
    Properties:
      VolumeType: !Ref VolumeType
      Size: !Ref VolumeSize
      Iops: !If [IopsVolumeType, !Ref Iops, !Ref 'AWS::NoValue']
      Throughput: !If [ThroughputApplicable, !Ref Throughput, !Ref 'AWS::NoValue']
      AvailabilityZone: !Ref AvailabilityZone
      Encrypted: !Ref Encrypted
      KmsKeyId: !If [KMSKeyNotProvided, !Ref 'AWS::NoValue', !Ref KmsKeyId]
      # AvailabilityZone: !Select [0, !GetAZs '']
      
      Tags: 
        - Key: cost_resource
          Value: !Sub ${AWS::StackName}
        - Key: researcher_name
          Value: !Ref ResearcherName
        - Key: project_name
          Value: !Ref ProjectId
        - Key: Name
          Value: !Join ['-', [Ref: Namespace, 'Volume']]
    DeletionPolicy: Snapshot

Outputs:
  VolumeId:
    Description: Volume id of newly created Ebs volume. 
    Value: !Ref VolumeId
  AvailabilityZone:   
    Description: location of newly created Ebs volume.
    Value: !Ref AvailabilityZone