AWSTemplateFormatVersion: 2010-09-09

Description: Sets up EFS on AWS
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: File system settings
        Parameters:                   
          - BackupPolicy
          - VpcId
          - SubnetId 
          - CidrIp
      - Label:
          default: Lifecycle management           
        Parameters:
          - TransitionIntoIA
          - TransitionToPrimaryStorageClass
          - PerformanceMode
          - ThroughputMode
          - ProvisionedThroughputInMibps 
      - Label:
          default: Encryption           
        Parameters:
          - Encrypted
          - KmsKeyId 

Parameters:          
  BackupPolicy: 
    Description: Automatically backup your file system data with AWS Backup using recommended settings. Additional pricing applies.
    Type: String 
    Default: DISABLED
    AllowedValues: [ENABLED,DISABLED]
  VpcId:
    Description: The ID of the VPC that the file system will be accessible from
    Type: AWS::EC2::VPC::Id
  SubnetId: 
    Description: The subnet where to launch the service 
    Type: AWS::EC2::Subnet::Id
  CidrIp:
    Description: The IP address range that can be used to access the file system.
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 0.0.0.0/0
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.     
  TransitionIntoIA:
    Description: Migrates files that have not been accessed for a set period of time to the EFS Standard–Infrequent Access (Standard-IA) or One Zone–Infrequent Access (One Zone-IA) storage class, depending on your file system.
    Type: String 
    Default: AFTER_60_DAYS
    AllowedValues: [AFTER_7_DAYS,AFTER_14_DAYS,AFTER_60_DAYS,AFTER_90_DAYS]
  TransitionToPrimaryStorageClass:
    Description: Automatically moves files back to the EFS Standard or EFS One Zone storage classes when the TransitionToPrimaryStorageClass lifecycle policy is set to On first access. This helps to eliminate the risk of unbounded access charges, while providing consistent low latencies.
    Type: String 
    Default: NONE
    AllowedValues: [AFTER_1_ACCESS, NONE]
  PerformanceMode:
    Description: >- 
      Amazon EFS delivers more than 10 gibibytes per second (GiBps) of throughput over 500,000 IOPS, and sub-millisecond or low single digit millisecond latencies.
      General Purpose mode supports up to 35,000 IOPS and has the lowest per-operation latency. File systems with EFS One Zone storage classes always use General Purpose performance mode.
      Max I/O mode supports 500,000+ IOPS and has higher per-operation latencies when compared to General Purpose mode.
    Type: String 
    Default: generalPurpose
    AllowedValues: [generalPurpose, maxIO]
  ThroughputMode:
    Description: >-
      determines the throughput available to your file system.
      Bursting Throughput mode is a good fit for traditional applications that have a bursty throughput pattern.
      In Provisioned Throughput mode, you specify a level of throughput that the file system can drive independent of the file system's size or burst credit balance.  
    Type: String 
    Default: bursting
    AllowedValues: [bursting, provisioned]
  ProvisionedThroughputInMibps: 
    Description: >-
      The amount of provisioned throughput, measured in MiB/s, for the file system. Valid for file systems using ThroughputMode set to provisioned.
      Valid range is 1-1024 MiB/s
    Type: Number 
    Default: 1    
  Encrypted:
    Description: Choose to enable encryption of your file system's data at rest. Uses the AWS KMS service key (aws/elasticfilesystem) by default
    Type: String 
    Default: false
    AllowedValues: [true, false]
  KmsKeyId:
    Description: The ID of the AWS Key Management Service (AWS KMS) key used to encrypt Amazon EFS file system data.
    Type: String
    Default: NONE      
  ResearcherName:
    Description: Researcher name that will be added as tag to the resources
    Type: String    
  ProjectId:
    Description: Project Id that will be added as tag to the resources
    Type: String    
  Namespace:
    Description: Name your file system. Name can include letters, numbers, and +-=._:/ symbols, up to 256 characters.
    Type: String

Conditions:    
  burstingThroughputMode: !Equals [!Ref ThroughputMode ,bursting]
  KMSKeyNotProvided: !Equals [!Ref KmsKeyId, 'NONE']
    
Resources: 
  EFSSecurityGroup:
      Type: "AWS::EC2::SecurityGroup"
      Properties:
        VpcId: !Ref VpcId
        SecurityGroupIngress:
          - CidrIp: !Ref CidrIp
            FromPort: 2049
            ToPort: 2049
            IpProtocol: tcp         
        GroupDescription: EFS Security Group

  FileSystem: 
        Type: AWS::EFS::FileSystem
        Properties:
          BackupPolicy:
            Status: !Ref BackupPolicy
          Encrypted: !Ref Encrypted
          KmsKeyId: !If [KMSKeyNotProvided, !Ref 'AWS::NoValue', !Ref KmsKeyId]
          LifecyclePolicies:
            - TransitionToIA: !Ref TransitionIntoIA
            - TransitionToPrimaryStorageClass: AFTER_1_ACCESS
          PerformanceMode: !Ref PerformanceMode          
          ThroughputMode: !Ref ThroughputMode
          ProvisionedThroughputInMibps: !If [burstingThroughputMode, !Ref 'AWS::NoValue', !Ref ProvisionedThroughputInMibps]    

          FileSystemTags: 
           - Key: Name
             Value: !Ref Namespace
           - Key: cost_resource
             Value: !Sub ${AWS::StackName}
           - Key: researcher_name
             Value: !Ref ResearcherName
           - Key: project_name
             Value: !Ref ProjectId
           - Key: Name
             Value: !Join ['-', [Ref: Namespace, 'file-system']]  
           
  MountTarget:
    Type: AWS::EFS::MountTarget
    Properties: 
        FileSystemId: !Ref FileSystem
        SubnetId: !Ref SubnetId
        SecurityGroups: 
          - !Ref EFSSecurityGroup           
Outputs:
  EFS:
    Description: The created EFS filesystem ID
    Value: !Ref FileSystem
  MountTarget:
    Description: MountTarget for the  created EFS filesystem. 
    Value: !Ref MountTarget        