AWSTemplateFormatVersion: '2010-09-09'
Description: create a single S3 bucket

Parameters:
  Namespace:
    Type: String
    Description: An environment name that will be prefixed to resource names 
  KMSKeyArn:
    Type: String
    Description: "If having KMS Key ARN, Pass ARN"
    Default: "Default"
  SSEAlgorithm:
    Type: String
    Description: "If KMS key ARN passed,select aws:kms Encryption algorithm"
    Default: "AES256"
    AllowedValues:
      - aws:kms
      - AES256
  AccessLoggingBucketName:
    Type: String
    Description: "Pass the bucket name where Access Logs for this S3 bucket should be sent"
    
Conditions:
  AES256: !Equals [!Ref SSEAlgorithm, "AES256"]   
  AccessLoggingEnabled:
    Fn::Not:
      - Fn::Equals:
          - Ref: AccessLoggingBucketName
          - ""
Resources:
  SampleBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref Namespace
      BucketEncryption: 
        ServerSideEncryptionConfiguration: 
        - !If
          - AES256
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: !Ref SSEAlgorithm
            BucketKeyEnabled: true
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: !Ref SSEAlgorithm
              KMSMasterKeyID: !Ref KMSKeyArn
            BucketKeyEnabled: true    
      Tags:
        - Key: cost_resource
          Value: !Sub ${AWS::StackName}
        - Key: Name
          Value: !Sub ${Namespace} 
      LoggingConfiguration:
        Fn::If:
          - AccessLoggingEnabled
          - DestinationBucketName: !Ref AccessLoggingBucketName
            LogFilePrefix: !Ref Namespace
          - !Ref "AWS::NoValue"

BucketPolicy:
  Type: "AWS::S3::BucketPolicy"
  Properties:
    Bucket: !Ref SampleBucket      
    PolicyDocument:
      Version: "2012-10-17"
      Statement:
        - Sid: EnforceTLS12
          Effect: Deny
          Principal: "*"
          Action: "s3:*"
          Resource:
            - !Sub "${SampleBucket.Arn}"
            - !Sub "${SampleBucket.Arn}/*"
          Condition:
            Bool:
              "aws:SecureTransport": "false"
        - Sid: EnforceTLS12OrHigher
          Effect: Deny
          Principal: "*"
          Action: "s3:*"
          Resource:
            - !Sub "${SampleBucket.Arn}"
            - !Sub "${SampleBucket.Arn}/*"
          Condition:
            NumericLessThan:
              "s3:TLSVersion": "1.2"

Outputs:
  BucketArn:
    Value: !GetAtt [SampleBucket, Arn]
    Description: URL for website hosted on S3
  BucketName:
    Value: !Ref SampleBucket
    Description: Name of S3 bucket